Subroutine Docs(uni)
Integer :: uni
        open(unit = 1  , file = 'CDF_Exp_3S1.txt', status = 'unknown')
        open(unit = 2  , file = 'CDF_Exp_1S0.txt', status = 'unknown')
        open(unit = 3  , file = 'SE_Exp.txt'     , status = 'unknown')
        open(unit = 4 , file  = 'CDF_V3S1.txt'   , status = 'unknown')
        open(unit = 5 , file  = 'CDF_N3S1.txt'   , status = 'unknown')
        open(unit = 6 , file  = 'CDF_V1S0.txt'   , status = 'unknown')
        open(unit = 7 , file  = 'CDF_N1S0.txt'   , status = 'unknown')
        open(unit = 8 , file  = 'Error.txt'      , status = 'unknown')
        open(unit = 9 , file  = 'SE_total_N.txt' , status = 'unknown')
        open(unit = 10 , file = 'SE_total_V.txt' , status = 'unknown')
        open(unit = 11 , file = 'Pot_3S1_N.txt'  , status = 'unknown')
        open(unit = 12 , file = 'Pot_1S0_N.txt'  , status = 'unknown')
        open(unit = 13 , file = 'Pot_3S1_V.txt'  , status = 'unknown')
        open(unit = 14 , file = 'Pot_1S0_V.txt'  , status = 'unknown')
        open(unit = 15 , file = '1MeV.txt'       , status = 'unknown')
        open(unit = 16 , file = '10MeV.txt'       , status = 'unknown')
        open(unit = 17 , file = '50MeV.txt'      , status = 'unknown')
        open(unit = 18 , file = '100MeV.txt'     , status = 'unknown')
        open(unit = 19 , file = '200MeV.txt'     , status = 'unknown')
        open(unit = 20 , file = '300MeV.txt'     , status = 'unknown')

        open(unit = 100, file = 'Potential.txt'       , status = 'unknown') 
end subroutine Docs